### ISSUE TITLE
Bug: require() of ES Module wav-file-decoder/dist/WavFileDecoder.js from lib/audio.js not supported.

### ISSUE THREAD

**Issue by initialencounter** [idanran/koishi-plugin-adapter-red#14]
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/109729945/a90f98b4-003c-47a4-a155-df5079c0f942)
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/109729945/a7906de8-7760-4abb-bf1f-72c77a76342d)
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/109729945/de60098b-5a1e-4ac0-9d54-eec835da127c)
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/109729945/ba05343b-d1b9-46cd-ba25-8974969013a6)

```
"koishi-plugin-adapter-red": "2.2.0",
"koishi": "4.15.3"
```

平台： Linux; Windows

日志：
```
2023-10-30 09:36:22 [W] config failed to load adapter-red
2023-10-30 09:36:22 [W] config Error [ERR_REQUIRE_ESM]: require() of ES Module /root/ks/node_modules/wav-file-decoder/dist/WavFileDecoder.js from /root/ks/node_modules/koishi-plugin-adapter-red/lib/audio.js not supported.
                        Instead change the require of WavFileDecoder.js in /root/ks/node_modules/koishi-plugin-adapter-red/lib/audio.js to a dynamic import() which is available in all CommonJS modules.
                            at Object.<anonymous> (/root/ks/node_modules/koishi-plugin-adapter-red/lib/audio.js:11:28)
                            at Object.<anonymous> (/root/ks/node_modules/koishi-plugin-adapter-red/lib/message.js:33:17)
                            at Object.<anonymous> (/root/ks/node_modules/koishi-plugin-adapter-red/lib/bot.js:7:19)
                            at Object.<anonymous> (/root/ks/node_modules/koishi-plugin-adapter-red/lib/index.js:3:15)
                            at Proxy.import (/root/ks/node_modules/@koishijs/loader/lib/index.js:89:12)
                            at Proxy.resolvePlugin (/root/ks/node_modules/@koishijs/loader/lib/shared.js:203:51)
                            at _PackageProvider.parseExports (/root/ks/node_modules/@koishijs/plugin-config/lib/shared/index.js:85:45)
                            at ctx.console.addListener.authority (/root/ks/node_modules/@koishijs/plugin-config/lib/shared/index.js:48:37)
                            at WebSocket.receive (/root/ks/node_modules/@koishijs/console/lib/index.js:127:45)
```

**Comment by idranme** [comment]
已在 2.2.1 解决
