### ISSUE TITLE
[Bug][3.0.1]Koishi 4.17.1，Adapter-red 3.0.1，响应命令时返回两条一模一样的消息

### ISSUE THREAD

**Issue by TheFairyTale** [idanran/koishi-plugin-adapter-red#21]
如题，观察发现当发出任何命令时（koishi 自带命令或第三方插件命令或由第三方定时主动发送的消息），koishi 会返回两条相同的响应，大约在达到插件设置->连接设置中"**初次连接时的最大重试次数**"设置的时间后koishi 后台会出现报错：
` session Error: timeout`及 ` session Error: fetch http://49.*.*.*:16510/api/message/send failed `
这两条报错在机器人返回消息后报出，且timeout 和fetch failed 报错各出现两次
看报错信息中还有SatoriJs，尚不清楚是否是koishi 自带的该基础插件造成的错误
已经测试在koishi后台的沙盒中不会重复响应消息
已经测试即使qqnt与koishi 处于同一主机通过127.0.0.1连接时仍有相同问题

koishi-plugin-adapter-red插件版本:  3.0.1
Chronocat.js 版本: v0.0.54
qqNT版本: 9.9.3-17816
**Koishi** 服务器信息：
System: OS: Windows Server 2012 6.3.9600
CPU: (2) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
Binaries:
 - Node: 18.17.1
 - npm: 9.6.7

Koishi:
 - Core: 4.17.1
 - Console: 5.28.0

**QQNT**所在服务器信息：
System: OS: Windows 10 10.0.20348
CPU: (4) x64 AMD EPYC 7K62 48-Core Processor
Binaries:
 - Node: 20.11.0
 - npm: 10.2.4

Koishi:
 - Core: 4.17.1
 - Console: 5.28.0

### 
### 重发两条消息造成的效果（第三方插件）：
![FF105D5F9474DD78E3913E9DF6490950](https://github.com/idanran/koishi-plugin-adapter-red/assets/16740355/1df2b91a-6b6f-4eb5-a81c-df52035ceb0b)

###
### 重发两条消息造成的效果（Koishi自带命令）：
![2AD60598C0483C21F82102D7221ED1E1](https://github.com/idanran/koishi-plugin-adapter-red/assets/16740355/f33db499-a3c5-4c5c-9c5e-74a824b5504d)

后台可以看到的报错代码：
```

2024-02-29 21:40:56 [W] session Error: timeout
                            at Object.fetch (node:internal/deps/undici/undici:11576:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:186:19)
                            at async Proxy.<anonymous> (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:74:26)
                            at async RedMessageEncoder.flush (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-adapter-red\lib\message.js:37:21)
                            at async RedMessageEncoder.send (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:561:5)
                            at async RedBot.sendMessage (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:326:22)
2024-02-29 21:40:56 [W] session Error: fetch http://49.*.*.*:16510/api/message/send failed
                            at C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:187:23

                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:186:19)
                            at async Proxy.<anonymous> (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:74:26)
                            at async RedMessageEncoder.flush (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-adapter-red\lib\message.js:37:21)
                            at async RedMessageEncoder.send (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:561:5)
                            at async RedBot.sendMessage (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:326:22)
2024-02-29 21:40:56 [W] session Error: timeout
                            at Object.fetch (node:internal/deps/undici/undici:11576:11)
                            at processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at runNextTicks (node:internal/process/task_queues:64:3)
                            at process.processTimers (node:internal/timers:509:9)
                            at async [cordis.invoke] (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:186:19)
                            at async Proxy.<anonymous> (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:74:26)
                            at async RedMessageEncoder.flush (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-adapter-red\lib\message.js:37:21)
                            at async RedMessageEncoder.send (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:561:5)
                            at async RedBot.sendMessage (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:326:22)
2024-02-29 21:40:56 [W] session Error: fetch http://49.*.*.*:16510/api/message/send failed
                            at C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:187:23
                            at processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at runNextTicks (node:internal/process/task_queues:64:3)
                            at process.processTimers (node:internal/timers:509:9)
                            at async [cordis.invoke] (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:186:19)
                            at async Proxy.<anonymous> (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:74:26)
                            at async RedMessageEncoder.flush (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-adapter-red\lib\message.js:37:21)
                            at async RedMessageEncoder.send (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:561:5)
                            at async RedBot.sendMessage (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:326:22)
2024-02-29 21:53:07 [W] session Error: timeout
                            at Object.fetch (node:internal/deps/undici/undici:11576:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:186:19)
                            at async Proxy.<anonymous> (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:74:26)
                            at async RedMessageEncoder.flush (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\koishi-plugin-adapter-red\lib\message.js:37:21)
                            at async RedMessageEncoder.send (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:561:5)
                            at async RedBot.sendMessage (C:\Users\Administrator\Desktop\koishi-app-dev\koishi-app_dev\node_modules\@satorijs\core\lib\index.cjs:326:22)
2024-02-29 21:53:07 [W] session Error: fetch http://49.*.*.*:16510/api/message/send failed
...
```

感谢您在百忙之中抽出时间回答该问题，谢谢您！

**Comment by idranme** [comment]
麻烦 QQ 加一下 590104798

**Comment by TheFairyTale** [comment]
已解决
尝试：
1.先退出登录QQ
2.重新打开QQNT，登录后再次尝试是否有上面的情况

如果还有该问题则尝试：
1.退出登录qq
2.删除 `C:\Users\你的用户名\Documents\Tencent Files\`  文件夹下 **该机器人QQ号** 的文件夹（比如我的QQ是987654321，当前登录的Windows 用户名为Admin，则删除`C:\Users\Admin\Documents\Tencent Files\987654321\` 文件夹）
3.重新打开QQNT，登录后再次尝试是否有上面的情况
