### ISSUE TITLE
(bug) 从 feishu 转发图片至 red 时报错

### ISSUE THREAD

**Issue by Mcayear** [idanran/koishi-plugin-adapter-red#22]
环境信息：
```
System:
    OS: Windows 10 10.0.20348
    CPU: (2) x64 QEMU Virtual CPU version 2.5+

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.3
    Console: 5.25.8
    Koishi Desktop: 1.0.2
```

插件信息：
```
adapter-red    3.1.0
adapter-lark     3.4.0
```

报错：
```
2024-04-04 12:18:20 [W] app TypeError: Cannot read properties of undefined (reading 'type')
                            at RedMessageEncoder.image (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-red\lib\message.js:89:26)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async RedMessageEncoder.visit (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-red\lib\message.js:263:17)
                            at async RedMessageEncoder.render (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:531:7)
                            at async RedMessageEncoder.send (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:560:5)
                            at async RedBot.sendMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:326:22)
```

**Comment by idranme** [comment]
qq 和 cc 的版本是多少

**Comment by Mcayear** [comment]
|         | 版本           |
|-------------|---------------|
| LiteLoader  | 1.0.3         |
| QQNT        | 9.9.7-21804   |
| Chromium    | 120.0.6099.56 |
| Electron    | 28.0.0        |
| Node.js     | 18.18.2       |

![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/785f850a-3d48-4ef3-aeb2-f98248c5d9cb)

**Comment by idranme** [comment]
chronocat 版本是多少

**Comment by Mcayear** [comment]
chronocat  0.1.1

![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/1f374da2-4bb4-4cac-ae34-7aa45311c6ed)

**Comment by idranme** [comment]
https://github.com/satorijs/satori/commit/1453fc95adbaf429ac41f86af37d45e2764231b6
adapter-lark 已尝试修复。
